# users controller
# user.rest_configuration.service:
#     class: "@SettingsBundle\Controller\RestController::index"
#     arguments:
#         - "@service_container"
#         - "@doctrine.orm.entity_manager"