stride_dashboard:
   path: /
   controller: App\Controller\DefaultController::index

# security routes
security_routes:
   resource: './security/security.yml'

setting_routes:
   resource: './settings/settings.yml'