stride_dashboard:
   path: /
   controller: App\Controller\DefaultController::index

# security routes
stride_security_routes:
   resource: './Routes/Security/Security.yml'

stride_system_routes:
   resource: './Routes/System/System.yml'

stride_setting_routes:
   resource: './Routes/Settings/Settings.yml'