imports:
   - { resource: './Entity/Repository/entity.yaml' }
   - { resource: './Entity/SearchableRepository/repository.yaml' }

parameters:
   setting.controller: App\Controller\Setting\SettingController

services:
   _defaults:
      autowire: true
      autoconfigure: true
      public: false
   stride_setting_controller:
      class: '%setting.controller%'
      autowire: true
      public: true
      # arguments:
      #    $entityManager: '@doctrine.orm.entity_manager'
      #    $currencySearchable: '@stride.searchable.currency.service'
   # alias
   # stride_setting_controller:
   #    alias: App\Controller\Setting\SettingController
   #    public: true