
app_routes:
   resource: '../../src/Resources/config/routing.yml'
# index:
#    path: /
#    controller: App\Controller\DefaultController::index

# _login:
#    path: /user/login
#    controller: App\Controller\DefaultController::userLogin
