user_Core:
  path: /Core
  controller: Stride\Core\Controller\RestController::index
  # controller: "@"

# sride user routings
stride_core_user:
  prefix: /stride/core
  resource: "@CoreBundle/Resources/config/routes/user.yaml"

# stride role routing
# stride_core_role:
#   resource: "@CoreBundle/Resources/config/routes/role.yaml"

# stride_core_user_group:
#   resource: "@CoreBundle/Resources/config/routes/usergroup.yaml"